# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Tornado Indexer
contracts:
  - name: TornadoCash_ETH_0_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_ETH_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_ETH_10
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_ETH_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_DAI_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_DAI_1000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_DAI_10000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_DAI_100000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_CDAI_5000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_CDAI_50000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_CDAI_500000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_CDAI_5000000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_USDC_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_USDC_1000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_USDT_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_USDT_1000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_WBTC_0_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_WBTC_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_WBTC_10
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_BNB_0_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_BNB_1
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_BNB_10
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_BNB_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_XDAI_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_XDAI_1000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_XDAI_10000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_XDAI_100000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_AVAX_10
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_AVAX_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_AVAX_500
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_MATIC_100
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_MATIC_1000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_MATIC_10000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_MATIC_100000
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)




networks:
# Mainnet
- id: 1
  start_block: 0
  contracts:

  # -----
  # ETH
  # -----

  - name: TornadoCash_ETH_0_1
    address: "0x12D66f87A04A9E220743712cE6d9bB1B5616B8Fc"
  - name: TornadoCash_ETH_1
    address: "0x47CE0C6eD5B0Ce3d3A51fdb1C52DC66a7c3c2936"
  - name: TornadoCash_ETH_10
    address: "0x910Cbd523D972eb0a6f4cAe4618aD62622b39DbF"
  - name: TornadoCash_ETH_100
    address: "0xA160cdAB225685dA1d56aa342Ad8841c3b53f291"

  # -----
  # DAI
  # -----

  - name: TornadoCash_DAI_100
    address: "0xD4B88Df4D29F5CedD6857912842cff3b20C8Cfa3"
  - name: TornadoCash_DAI_1000
    address: "0xFD8610d20aA15b7B2E3Be39B396a1bC3516c7144"
  - name: TornadoCash_DAI_10000
    address: "0x07687e702b410Fa43f4cB4Af7FA097918ffD2730"
  - name: TornadoCash_DAI_100000
    address: "0x23773E65ed146A459791799d01336DB287f25334"

  # -----
  # CDAI
  # -----

  - name: TornadoCash_CDAI_5000
    address: "0x22aaA7720ddd5388A3c0A3333430953C68f1849b"
  - name: TornadoCash_CDAI_50000
    address: "0x03893a7c7463AE47D46bc7f091665f1893656003"
  - name: TornadoCash_CDAI_500000
    address: "0x2717c5e28cf931547B621a5dddb772Ab6A35B701"
  - name: TornadoCash_CDAI_5000000
    address: "0xD21be7248e0197Ee08E0c20D4a96DEBdaC3D20Af"

  # -----
  # USDC
  # -----

  - name: TornadoCash_USDC_100
    address: "0xd96f2B1c14Db8458374d9Aca76E26c3D18364307"
  - name: TornadoCash_USDC_1000
    address: "0x4736dCf1b7A3d580672CcE6E7c65cd5cc9cFBa9D"

  # -----
  # USDT
  # -----

  - name: TornadoCash_USDT_100
    address: "0x169AD27A470D064DEDE56a2D3ff727986b15D52B"
  - name: TornadoCash_USDT_1000
    address: "0x0836222F2B2B24A3F36f98668Ed8F0B38D1a872f"

  # -----
  # WBTC
  # -----

  - name: TornadoCash_WBTC_0_1
    address: "0x178169B423a011fff22B9e3F3abeA13414dDD0F1"
  - name: TornadoCash_WBTC_1
    address: "0x610B717796ad172B316836AC95a2ffad065CeaB4"
  - name: TornadoCash_WBTC_10
    address: "0xbB93e510BbCD0B7beb5A853875f9eC60275CF498"
      
# Goerli
- id: 5
  start_block: 0
  contracts:
    
  # -----
  # ETH
  # -----

  - name: TornadoCash_ETH_0_1
    address: "0x6Bf694a291DF3FeC1f7e69701E3ab6c592435Ae7"
  - name: TornadoCash_ETH_1
    address: "0x3aac1cC67c2ec5Db4eA850957b967Ba153aD6279"
  - name: TornadoCash_ETH_10
    address: "0x723B78e67497E85279CB204544566F4dC5d2acA0"
  - name: TornadoCash_ETH_100
    address: "0x0E3A09dDA6B20aFbB34aC7cD4A6881493f3E7bf7"

  # -----
  # DAI
  # -----

  - name: TornadoCash_DAI_100
    address: "0x76D85B4C0Fc497EeCc38902397aC608000A06607"
  - name: TornadoCash_DAI_1000
    address: "0xCC84179FFD19A1627E79F8648d09e095252Bc418"
  - name: TornadoCash_DAI_10000
    address: "0xD5d6f8D9e784d0e26222ad3834500801a68D027D"
  - name: TornadoCash_DAI_100000
    address: "0x407CcEeaA7c95d2FE2250Bf9F2c105aA7AAFB512"

  # -----
  # CDAI
  # -----

  - name: TornadoCash_CDAI_5000
    address: "0x833481186f16Cece3f1Eeea1a694c42034c3a0dB"
  - name: TornadoCash_CDAI_50000
    address: "0xd8D7DE3349ccaA0Fde6298fe6D7b7d0d34586193"
  - name: TornadoCash_CDAI_500000
    address: "0x8281Aa6795aDE17C8973e1aedcA380258Bc124F9"
  - name: TornadoCash_CDAI_5000000
    address: "0x57b2B8c82F065de8Ef5573f9730fC1449B403C9f"
      
  # -----
  # USDC
  # -----

  - name: TornadoCash_USDC_100
    address: "0x05E0b5B40B7b66098C2161A5EE11C5740A3A7C45"
  - name: TornadoCash_USDC_1000
    address: "0x23173fE8b96A4Ad8d2E17fB83EA5dcccdCa1Ae52"

  # -----
  # USDT
  # -----

  - name: TornadoCash_USDT_100
    address: "0x538Ab61E8A9fc1b2f93b3dd9011d662d89bE6FE6"
  - name: TornadoCash_USDT_1000
    address: "0x94Be88213a387E992Dd87DE56950a9aef34b9448"

  # -----
  # WBTC
  # -----

  - name: TornadoCash_WBTC_0_1
    address: "0x242654336ca2205714071898f67E254EB49ACdCe"
  - name: TornadoCash_WBTC_1
    address: "0x776198CCF446DFa168347089d7338879273172cF"
  - name: TornadoCash_WBTC_10
    address: "0xeDC5d01286f99A066559F60a585406f3878a033e"

# BNB
- id: 56
  start_block: 0
  contracts:
    
    # -----
    # BNB
    # -----

    - name: TornadoCash_BNB_0_1
      address: "0x84443CFd09A48AF6eF360C6976C5392aC5023a1F"
    - name: TornadoCash_BNB_1
      address: "0xd47438C816c9E7f2E2888E060936a499Af9582b3"
    - name: TornadoCash_BNB_10
      address: "0x330bdFADE01eE9bF63C209Ee33102DD334618e0a"
    - name: TornadoCash_BNB_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"

# XDAI
- id: 100
  start_block: 0
  contracts:
    
    # -----
    # XDAI
    # -----

    - name: TornadoCash_XDAI_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"
    - name: TornadoCash_XDAI_1000
      address: "0xdf231d99Ff8b6c6CBF4E9B9a945CBAcEF9339178"
    - name: TornadoCash_XDAI_10000
      address: "0xaf4c0B70B2Ea9FB7487C7CbB37aDa259579fe040"
    - name: TornadoCash_XDAI_100000
      address: "0xa5C2254e4253490C54cef0a4347fddb8f75A4998"

# Matic
- id: 137
  start_block: 0
  contracts:
    
    # -----
    # MATIC
    # -----

    - name: TornadoCash_MATIC_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"
    - name: TornadoCash_MATIC_1000
      address: "0xdf231d99Ff8b6c6CBF4E9B9a945CBAcEF9339178"
    - name: TornadoCash_MATIC_10000
      address: "0xaf4c0B70B2Ea9FB7487C7CbB37aDa259579fe040"
    - name: TornadoCash_MATIC_100000
      address: "0xa5C2254e4253490C54cef0a4347fddb8f75A4998"


# Arbitrum
- id: 42161
  start_block: 0
  contracts:
    
    # -----
    # ETH
    # -----

    - name: TornadoCash_ETH_0_1
      address: "0x84443CFd09A48AF6eF360C6976C5392aC5023a1F"
    - name: TornadoCash_ETH_1
      address: "0xd47438C816c9E7f2E2888E060936a499Af9582b3"
    - name: TornadoCash_ETH_10
      address: "0x330bdFADE01eE9bF63C209Ee33102DD334618e0a"
    - name: TornadoCash_ETH_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"


# Avalanche
- id: 43114
  start_block: 0
  contracts:
    
    # -----
    # AVAX
    # -----

    - name: TornadoCash_AVAX_10
      address: "0x330bdFADE01eE9bF63C209Ee33102DD334618e0a"
    - name: TornadoCash_AVAX_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"
    - name: TornadoCash_AVAX_500
      address: "0xaf8d1839c3c67cf571aa74B5c12398d4901147B3"


# Optimism
- id: 10
  start_block: 0
  contracts:
    
    # -----
    # ETH
    # -----

    - name: TornadoCash_ETH_0_1
      address: "0x84443CFd09A48AF6eF360C6976C5392aC5023a1F"
    - name: TornadoCash_ETH_1
      address: "0xd47438C816c9E7f2E2888E060936a499Af9582b3"
    - name: TornadoCash_ETH_10
      address: "0x330bdFADE01eE9bF63C209Ee33102DD334618e0a"
    - name: TornadoCash_ETH_100
      address: "0x1E34A77868E19A6647b1f2F47B51ed72dEDE95DD"

