# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Tornado Indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: TornadoCash_ETH_0_1
    address:
    - 0x12D66f87A04A9E220743712cE6d9bB1B5616B8Fc
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_ETH_1
    address:
    - 0x47CE0C6eD5B0Ce3d3A51fdb1C52DC66a7c3c2936
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
  - name: TornadoCash_DAI_100
    address:
    - 0xD4B88Df4D29F5CedD6857912842cff3b20C8Cfa3
    handler: src/EventHandlers.ts
    events:
    - event: Deposit(bytes32 indexed commitment, uint32 leafIndex, uint256 timestamp)
    - event: Withdrawal(address to, bytes32 nullifierHash, address indexed relayer, uint256 fee)
